pull_request_rules:

  # ===============================================================================
  # DEPENDABOT
  # ===============================================================================

  - name: Automatic Merge for Dependabot Minor Version Pull Requests
    conditions:
      - -draft
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success='test (1.22.x, ubuntu-latest)'
      - title~=bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot pull request
      merge:
        method: rebase
  - name: Alert on major version detection
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success='test (1.22.x, ubuntu-latest)'
      - -title~=bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      comment:
        message: "⚠️ @wheresalice: this is a major version bump and requires your attention"

  # ===============================================================================
  # AUTOMATIC MERGE (APPROVALS)
  # ===============================================================================

  - name: Automatic Merge ⬇️ on Approval ✔
    conditions:
      - "#approved-reviews-by>=1"
      - check-success='test (1.22.x, ubuntu-latest)'
      - label!=work-in-progress
      - -draft
    actions:
      merge:
        method: rebase

  # ===============================================================================
  # AUTHOR
  # ===============================================================================

  - name: Auto-Assign Author
    conditions:
      - "#assignee=0"
    actions:
      assign:
        users: ["wheresalice"]

  # ===============================================================================
  # ALERTS
  # ===============================================================================

  - name: Notify on merge
    conditions:
      - merged
      - label=automerge
    actions:
      comment:
        message: "✅ @{{author}}: **{{title}}** has been merged successfully."
  - name: Alert on merge conflict
    conditions:
      - conflict
      - label=automerge
    actions:
      comment:
        message: "🆘 @{{author}}: `{{head}}` has conflicts with `{{base}}` that must be resolved."
  - name: Alert on tests failure for automerge
    conditions:
      - label=automerge
      - status-failure=commit
    actions:
      comment:
        message: "🆘 @{{author}}: unable to merge due to CI failure."

  # ===============================================================================
  # BRANCHES
  # ===============================================================================

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:

